services:
  react-app:
    build:
      target: prod
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    ports:
      - "0.0.0.0:${PORT:-8081}:80"